### ISSUE TITLE
[19w40a] Method _initGlfw does not decompile

### ISSUE THREAD

**Issue by liach** [FabricMC/procyon#11]
The method `LongSupplier _initGlfw()` in `com.mojang.blaze3d.platform.GLX` does not decompile. Moved from FabricMC/yarn#902

```
 // The error that occurred was:
        // 
        // java.lang.NullPointerException
        //     at com.strobel.decompiler.ast.AstBuilder.convertLocalVariables(AstBuilder.java:2895)
        //     at com.strobel.decompiler.ast.AstBuilder.performStackAnalysis(AstBuilder.java:2445)
        //     at com.strobel.decompiler.ast.AstBuilder.build(AstBuilder.java:108)
        //     at com.strobel.decompiler.languages.java.ast.AstMethodBodyBuilder.createMethodBody(AstMethodBodyBuilder.java:211)
        //     at com.strobel.decompiler.languages.java.ast.AstMethodBodyBuilder.createMethodBody(AstMethodBodyBuilder.java:99)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.createMethodBody(AstBuilder.java:782)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.createMethod(AstBuilder.java:675)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.addTypeMembers(AstBuilder.java:552)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeCore(AstBuilder.java:519)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeNoCache(AstBuilder.java:161)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.createType(AstBuilder.java:150)
        //     at com.strobel.decompiler.languages.java.ast.AstBuilder.addType(AstBuilder.java:125)
        //     at cuchaz.enigma.SourceProvider.getSources(SourceProvider.java:73)
        //     at cuchaz.enigma.gui.GuiController.decompileSource(GuiController.java:401)
        //     at cuchaz.enigma.gui.GuiController.lambda$loadClass$12(GuiController.java:387)
        //     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        //     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        //     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        //     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        //     at java.lang.Thread.run(Thread.java:748)
        // 
```

**Comment by MajickTek** [comment]
Posting the bytecode log shortly, just waiting on gradle

**Comment by MajickTek** [comment]
Alright here it is:

~~~~Java
public static LongSupplier _initGlfw() {
        // 
        // This method could not be decompiled.
        // 
        // Original Bytecode:
        // 
        //     5: invokestatic    com/mojang/blaze3d/systems/RenderSystem.assertThread:(Ljava/util/function/Supplier;)V
        //     8: invokedynamic   BootstrapMethod #2, accept:()Ljava/util/function/BiConsumer;
        //    13: invokestatic    net/minecraft/class_1041.method_4492:(Ljava/util/function/BiConsumer;)V
        //    16: invokestatic    com/google/common/collect/Lists.newArrayList:()Ljava/util/ArrayList;
        //    19: astore_0        /* list_1 */
        //    20: aload_0         /* list_1 */
        //    21: invokedynamic   BootstrapMethod #3, invoke:(Ljava/util/List;)Lorg/lwjgl/glfw/GLFWErrorCallbackI;
        //    26: invokestatic    org/lwjgl/glfw/GLFW.glfwSetErrorCallback:(Lorg/lwjgl/glfw/GLFWErrorCallbackI;)Lorg/lwjgl/glfw/GLFWErrorCallback;
        //    29: astore_1        /* gLFWErrorCallback_1 */
        //    30: invokestatic    org/lwjgl/glfw/GLFW.glfwInit:()Z
        //    33: ifeq            87
        //    36: invokedynamic   BootstrapMethod #4, getAsLong:()Ljava/util/function/LongSupplier;
        //    41: astore_2        /* longSupplier_1 */
        //    42: aload_0         /* list_1 */
        //    43: invokeinterface java/util/List.iterator:()Ljava/util/Iterator;
        //    48: astore_3       
        //    49: aload_3        
        //    50: invokeinterface java/util/Iterator.hasNext:()Z
        //    55: ifeq            84
        //    58: aload_3        
        //    59: invokeinterface java/util/Iterator.next:()Ljava/lang/Object;
        //    64: checkcast       Ljava/lang/String;
        //    67: astore          string_1
        //    69: getstatic       com/mojang/blaze3d/platform/GLX.LOGGER:Lorg/apache/logging/log4j/Logger;
        //    72: ldc             "GLFW error collected during initialization: {}"
        //    74: aload           string_1
        //    76: invokeinterface org/apache/logging/log4j/Logger.error:(Ljava/lang/String;Ljava/lang/Object;)V
        //    81: goto            49
        //    84: goto            122
        //    87: new             Ljava/lang/IllegalStateException;
        //    90: dup            
        //    91: new             Ljava/lang/StringBuilder;
        //    94: dup            
        //    95: invokespecial   java/lang/StringBuilder.<init>:()V
        //    98: ldc             "Failed to initialize GLFW, errors: "
        //   100: invokevirtual   java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
        //   103: ldc             ","
        //   105: invokestatic    com/google/common/base/Joiner.on:(Ljava/lang/String;)Lcom/google/common/base/Joiner;
        //   108: aload_0         /* list_1 */
        //   109: invokevirtual   com/google/common/base/Joiner.join:(Ljava/lang/Iterable;)Ljava/lang/String;
        //   112: invokevirtual   java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
        //   115: invokevirtual   java/lang/StringBuilder.toString:()Ljava/lang/String;
        //   118: invokespecial   java/lang/IllegalStateException.<init>:(Ljava/lang/String;)V
        //   121: athrow         
        //   122: aload_1         /* gLFWErrorCallback_1 */
        //   123: invokestatic    com/mojang/blaze3d/systems/RenderSystem.setErrorCallback:(Lorg/lwjgl/glfw/GLFWErrorCallbackI;)V
        //   126: aload_2         /* longSupplier_2 */
        //   127: areturn        
        //    StackMapTable: 00 04 FF 00 31 00 04 00 07 00 B7 07 00 B9 07 00 BB 00 00 FA 00 22 FF 00 02 00 01 07 00 CF 00 00 FF 00 22 00 03 00 07 00 B7 07 00 B9 00 00
   
        throw new IllegalStateException("An error occurred while decompiling this method.");
    }
~~~~

**Comment by MajickTek** [comment]
I can confirm this issue exists in 19w41a

**Comment by MajickTek** [comment]
Using CFR and a bit of "hacking" around, I was able to determine that the code should be like this:

~~~~Java
public static LongSupplier _initGlfw() {
        LongSupplier longSupplier;
        RenderSystem.assertThread(RenderSystem::isInInitPhase);
        Window.checkGlfwError((n, string) -> {
            throw new IllegalStateException(String.format("GLFW error before init: [0x%X]%s", n, string));
        });
        ArrayList arrayList = Lists.newArrayList();
        GLFWErrorCallback gLFWErrorCallback = GLFW.glfwSetErrorCallback((n, l) -> arrayList.add(String.format("GLFW error during init: [0x%X]%s", n, l)));
        if (GLFW.glfwInit()) {
            longSupplier = () -> (long)(GLFW.glfwGetTime() * 1.0E9);
            for (String string2 : arrayList) {
                LOGGER.error("GLFW error collected during initialization: {}", (Object)string2);
            }
        } else {
            throw new IllegalStateException("Failed to initialize GLFW, errors: " + Joiner.on((String)",").join((Iterable)arrayList));
        }
        RenderSystem.setErrorCallback((GLFWErrorCallbackI)gLFWErrorCallback);
        return longSupplier;
    }
~~~~

No idea why procyon can't handle this code.
(by the way this was using Mojang's official proguard mappings on 19w41a).

Edit: Mojang stated https://www.minecraft.net/en-us/article/programmers-play-minecrafts-inner-workings that Blaze3D will be open-source eventually so I'm super interested in this
